
export const GET_RESTAURANT_ORDER_REQUEST = "GET_RESTAURANT_ORDER_REQUEST";
export const GET_RESTAURANT_ORDER_SUCCESS = "GET_RESTAURANT_ORDER_SUCCESS";
export const GET_RESTAURANT_ORDER_FAIL = "GET_RESTAURANT_ORDER_FAIL";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";


export const UPDATE_ORDER_STATUS_OPTIMISTIC = "UPDATE_ORDER_STATUS_OPTIMISTIC";
