export const GET_SAVED_ADDRESSES_REQUEST = "GET_SAVED_ADDRESSES_REQUEST";
export const GET_SAVED_ADDRESSES_SUCCESS = "GET_SAVED_ADDRESSES_SUCCESS";
export const GET_SAVED_ADDRESSES_FAIL = "GET_SAVED_ADDRESSES_FAIL";
