export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";


export const GET_ALL_RESTAURANT_REQUEST = "GET_ALL_RESTAURANT_REQUEST";
export const GET_ALL_RESTAURANT_SUCCESS = "GET_ALL_RESTAURANT_SUCCESS";
export const GET_ALL_RESTAURANT_FAIL = "GET_ALL_RESTAURANT_FAIL";


export const SEARCH_RESTAURANT_REQUEST = "SEARCH_RESTAURANT_REQUEST";
export const SEARCH_RESTAURANT_SUCCESS = "SEARCH_RESTAURANT_SUCCESS";
export const SEARCH_RESTAURANT_FAIL = "SEARCH_RESTAURANT_FAIL";


export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";


export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAIL = "UPDATE_RESTAURANT_FAIL";


export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAIL = "GET_RESTAURANT_BY_ID_FAIL";

export const GET_RESTAURANT_BY_USER_ID_REQUEST = "GET_RESTAURANT_BY_USER_ID_REQUEST";
export const GET_RESTAURANT_BY_USER_ID_SUCCESS = "GET_RESTAURANT_BY_USER_ID_SUCCESS";
export const GET_RESTAURANT_BY_USER_ID_FAIL = "GET_RESTAURANT_BY_USER_ID_FAIL";


export const UPDATE_RESTAURANT_STATUS_REQUEST = "UPDATE_RESTAURANT_STATUS_REQUEST";
export const UPDATE_RESTAURANT_STATUS_SUCCESS = "UPDATE_RESTAURANT_STATUS_SUCCESS";
export const UPDATE_RESTAURANT_STATUS_FAIL = "UPDATE_RESTAURANT_STATUS_FAIL";

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const GET_RESTAURANT_EVENT_REQUEST = "GET_RESTAURANT_EVENT_REQUEST";
export const GET_RESTAURANT_EVENT_SUCCESS = "GET_RESTAURANT_EVENT_SUCCESS";
export const GET_RESTAURANT_EVENT_FAIL = "GET_RESTAURANT_EVENT_FAIL";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const GET_RESTAURANT_CATEGORY_REQUEST = "GET_RESTAURANT_CATEGORY_REQUEST";
export const GET_RESTAURANT_CATEGORY_SUCCESS = "GET_RESTAURANT_CATEGORY_SUCCESS";
export const GET_RESTAURANT_CATEGORY_FAIL = "GET_RESTAURANT_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';