export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';

export const GET_RESTAURANT_REVIEWS_REQUEST = 'GET_RESTAURANT_REVIEWS_REQUEST';
export const GET_RESTAURANT_REVIEWS_SUCCESS = 'GET_RESTAURANT_REVIEWS_SUCCESS';
export const GET_RESTAURANT_REVIEWS_FAIL = 'GET_RESTAURANT_REVIEWS_FAIL';

export const GET_AVERAGE_RATING_REQUEST = 'GET_AVERAGE_RATING_REQUEST';
export const GET_AVERAGE_RATING_SUCCESS = 'GET_AVERAGE_RATING_SUCCESS';
export const GET_AVERAGE_RATING_FAIL = 'GET_AVERAGE_RATING_FAIL';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';

export const GET_ORDER_REVIEW_REQUEST = "GET_ORDER_REVIEW_REQUEST";
export const GET_ORDER_REVIEW_SUCCESS = "GET_ORDER_REVIEW_SUCCESS";
export const GET_ORDER_REVIEW_FAIL = "GET_ORDER_REVIEW_FAIL";